name: dart_postgres_wrapper
description: A simple database wrapper.
version: 1.0.9
homepage: https://stekolschikovv.github.io
author: Vitaly Stekolschikov  <v.a.stekolschikov@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  postgres: ^1.0.2
  csv: ^4.0.1

dev_dependencies:
  test: ^1.0.0
